<?php

use App\Http\Controllers\AboutUsController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\ClassTypeController;

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Models\ClassType;



Route::get('/about-us/{id?}', [AboutUsController::class, 'index'])->name('about-us');
//Route::get('/about', function () {
//    return view('about');
//})->name('about');


Route::get('/', [HomeController::class, 'showHomeView'])->name('home');

Route::get('/about-us/{id?}', [AboutUsController::class, 'index'])->name('about-us');

Route::get('/contact', [ContactController::class, 'showContactView'])->name('contact');

//Route::get('/specialisations', [SpecialisationsController::class, 'showSpecialisationsView'])->name('specialisations');

Route::resource('classTypes', ClassTypeController::class);
Route::resource('class_types', ClassTypeController::class);
Route::get('/class-types', [ClassTypeController::class, 'index'])->name('classTypes.index');
Route::get('/class-types/filter', [ClassTypeController::class, 'filter'])->name('classTypes.filter');


Route::get('/contact', function() {
    return view('contact');
})->name('contact');


//Route::get('/', function () {
//    return view('home');
//});


// Authentication and Profile Routes with Middleware
Route::middleware('auth')->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

// Include Auth routes generated by Breeze
require __DIR__.'/auth.php';





//Route::get('/dashboard', function () {
//    return view('dashboard');
//})->middleware(['auth', 'verified'])->name('dashboard');
//
//
//Route::middleware('auth')->group(function () {
//    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
//    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
//    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
//});
//require __DIR__.'/auth.php';
//
